---
# tasks file for wireguard

- name: Install wireguard packages
  yum:
    name: '{{ wireguard_packages }}'
    state: present
  tags: install-only

- name: ensure wireguard configuration dir exists (/etc/wireguard)
  file:
    path: '/etc/wireguard'
    state: directory

- name: Generate interface keys
  shell: 'wg genkey | tee /etc/wireguard/private_key | wg pubkey > /etc/wireguard/public_key'
  args:
    creates: '/etc/wireguard/public_key'

- name: Ensure private key has correct permissions
  file:
    path: '/etc/wireguard/private_key'
    owner: 'root'
    group: 'root'
    mode: '0600'

- meta: end_play
  when: wg_genkey

- name: Read private key from file
  set_fact:
    wg_private_key: '{{ lookup("file", "/etc/wireguard/private_key") }}'

- name: Render interface configuration file
  template:
    src: '{{ "server-wg0.conf" if wg_server else "client-wg0.conf" }}'
    dest: '/etc/wireguard/wg0.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
    backup: yes
  notify: restart wg0

- name: Enable ip packet forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_set: yes
    reload: yes

- name: Enable arp proxying
  sysctl:
    name: net.ipv4.conf.all.proxy_arp
    value: 1
    state: present
    sysctl_set: yes
    reload: yes

- name: Enable and start wg0 interface service
  service:
    name: 'wg-quick@wg0'
    state: started
    enabled: yes

- meta: flush_handlers
