---
title: "Remote Desktop"
cluster: {{ cluster_name }}
attributes:
  bc_account:
    help: "this should be left blank most of the time"
  desktop: "{{ vnc_desktop }}"
  bc_vnc_idle:
    value: {{ vnc_idle_timeout }}
    label: "Idle timeout"
    help: This is the time you have to connect to a session before it is automatically terminated
form:
  - bc_vnc_idle
  - desktop
  - bc_account
  - bc_num_hours
  - bc_num_slots
  - node_type
  - bc_queue
  - bc_vnc_resolution
  - bc_email_on_started
