---
- hosts: controller

  roles:
    - role: trinity/repos
      repos:
      - repo: epel-release
      - repo: https://updates.clustervision.com/luna/1.2/centos/luna-1.2.repo
      tags: repos

    - role: trinity/packages
      tags: packages

    - role: trinity/hostname
      tags: hostname

    - role: cloud/wireguard
      tags: wireguard

    - role: trinity/firewalld
      firewalld_trusted_interfaces:
        - '{{ ansible_default_ipv4.interface }}'
        - wg0
      firewalld_update_ifcfg_files: false
      firewalld_masquerade_zone:
      firewalld_direct_rules:
        - rule: "! -s {{ wg_peer_address }}/32 -o {{ ansible_default_ipv4.interface }} -j MASQUERADE"
          ipver: ipv4
          table: nat
          chain: POSTROUTING
          priority: 0
      tags: firewalld

    - role: trinity/chrony
      chrony_upstream_servers:
      - '{{ onpremise_ctrl_ip }}'
      tags: chrony

    - role: trinity/rsyslog
      syslog_forwarding_rules:
      - name: default
        proto: 'tcp'
        port: 514
        host: '{{ onpremise_ctrl_ip }}'
        facility: '*'
        level: '*'
      tags: rsyslog

    - role: trinity/zabbix_agent
      trix_ctrl_ip: '{{ onpremise_ctrl_ip }}'
      zabbix_hostmetadata: gateway
      tags: zabbix_agent

    - role: trinity/bind
      bind_dnssec_enable: no
      bind_dns_forwarders:
        - '{{ onpremise_ctrl_ip }}'
      resolv_search_domains: '{{ onpremise_domain }} ipmi cloud'
      resolv_server: '{{ onpremise_ctrl_ip }}'
      tags: bind
