---
- name: Set compute variable
  set_fact:
    compute: '{{ True if (ansible_connection not in "lchroot" and "ood" not in group_names and "logins" not in group_names) else False }}'
  tags: always

- name: 'ensure cloud init services are disabled as these interfere with weka networking and cause long timeouts on reboot'
  service:
    name: '{{ item }}'
    enabled: false
  with_items:
    - 'cloud-init'
    - 'cloud-init-local'
    - 'cloud-config'
    - 'cloud-final'
  when: disable_cloud_init|bool

- name: check if /usr/bin/firewall-cmd exists
  stat:
    path: "/usr/bin/firewall-cmd"
  register: firewalld

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
  when: compute|default(False) and firewalld.stat.exists

- name: Disable firewalld
# service:
#   name: firewalld
#   enabled: no
  file:
    path: '/etc/systemd/system/multi-user.target.wants/firewalld.service'
    state: absent

- name: Get image name
  set_fact:
    image_name: '{{ inventory_hostname.split(".")|first }}'

- name: Generate salt for the root password
  set_fact:
    password_salt: "{{ lookup('password',
                '/etc{{trix_root}}/passwords/images/' + image_name + '/root-salt.txt
                chars=ascii_letters,digits,hexdigits length=16') }}"

- name: Setup the root user's password
  user:
    name: root
    password: '{{ lookup("password","/etc{{trix_root}}/passwords/images/" +image_name
              + "/root.txt")|password_hash("sha512", password_salt) }}'

    state: present

- name: Generate host SSH keys
  shell: ssh-keygen -A
  args:
    creates: /etc/ssh/ssh_host_rsa_key

- name: Disable host key check between nodes
  blockinfile:
    path: "/etc/ssh/ssh_config"
    block: |
      # Names without domain, such as node001
      host  * !*.*
              ForwardX11 yes
              CheckHostIP no
              HostbasedAuthentication no
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null

      # Our local domains
      Host  *.cluster *.ib
              ForwardX11 yes
              CheckHostIP no
              HostbasedAuthentication no
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null

- name: Use the controller as a DNS resolver
  template:
    src: "resolv.conf"
    dest: "/etc/resolv.conf"

- name: Set the default gateway (to controller node unless the default_gateway var is overridden)
  lineinfile:
    path: "/etc/sysconfig/network"
    line: "GATEWAY={{ default_gateway }}"
    regexp: "^[ \t]*GATEWAY"
    state: present
    create: yes
  notify: restart network

- name: Get the controller's timezone
  stat:
    path: "/etc/localtime"
  register: tz
  delegate_to: localhost

- name: Set the image/node's timezone
  file:
    src: "{{ tz.stat.lnk_source }}"
    dest: "/etc/localtime"
    state: link
