---
# vars file for nfs

nfs_packages:
  - nfs-utils

nfs_enable_rdma: false
nfs_mounts:
  - path: '{{ trix_shared }}'
    remote: 'controller:{{ trix_shared }}'
    options: 'defaults,nfsvers=4,ro,retrans=4'
