---
# tasks file for firewalld

- name: Install firewalld packages
  yum:
    name: '{{ firewalld_packages }}'
    state: present
  tags: install-only

- name: Start and enable firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Assign interfaces to the public zone
  firewalld:
    zone: public
    interface: '{{ item }}'
    state: enabled
    permanent: true
    immediate: true
  with_items: '{{ firewalld_public_interfaces }}'

- name: Update ifcfg files for interfaces '{{ firewalld_public_interfaces }}'
  lineinfile:
    path: '/etc/sysconfig/network-scripts/ifcfg-{{ item }}'
    regexp: '^ZONE='
    line: 'ZONE=public'
  with_items: '{{ firewalld_public_interfaces }}'
  when: firewalld_update_ifcfg_files

- name: Assign interfaces to the trusted zone
  firewalld:
    zone: trusted
    interface: '{{ item }}'
    state: enabled
    permanent: true
    immediate: true
  with_items: '{{ firewalld_trusted_interfaces }}'

- name: Update ifcfg files for interfaces '{{ firewalld_trusted_interfaces }}'
  lineinfile:
    path: '/etc/sysconfig/network-scripts/ifcfg-{{ item }}'
    regexp: '^ZONE='
    line: 'ZONE=trusted'
  with_items: '{{ firewalld_trusted_interfaces }}'
  when: firewalld_update_ifcfg_files

- name: Disable NetworkManager for public and trusted interfaces
  lineinfile:
    path: '/etc/sysconfig/network-scripts/ifcfg-{{ item }}'
    regexp: '^NM_CONTROLLED='
    line: 'NM_CONTROLLED=no'
  with_flattened:
    - '{{ firewalld_public_interfaces }}'
    - '{{ firewalld_trusted_interfaces }}'
  when: firewalld_update_ifcfg_files

- name: Enable masquerading on the '{{ firewalld_masquerade_zone }}' zone
  firewalld:
    zone: '{{ firewalld_masquerade_zone }}'
    masquerade: yes
    state: enabled
    permanent: true
    immediate: true
  when: firewalld_masquerade_zone is defined

- name: Configure open TCP ports on the public zone
  firewalld:
    zone: public
    port: '{{ item }}/tcp'
    state: enabled
    permanent: true
    immediate: true
  with_items: '{{ firewalld_public_tcp_ports }}'

- name: Configure open UDP ports on the public zone
  firewalld:
    zone: public
    port: '{{ item }}/udp'
    state: enabled
    permanent: true
    immediate: true
  with_items: '{{ firewalld_public_udp_ports }}'

- name: Add direct rules
  template:
    src: 'direct-rules.xml'
    dest: '/etc/firewalld/direct.xml'
  when: firewalld_direct_rules
  notify: reload firewalld

