---
- name: restart zabbix-server
  systemd:
    name: zabbix-server.service
    state: restarted
  when: primary | default(True)

- name: restart php-fpm
  systemd:
    name: php-fpm.service
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  when: primary|default(True)
