---
# Install additional packages and tunables

- name: Copy 91-hpc-limits.conf to /etc/security/limits.d
  template:
    src: '91-hpc-limits.conf.j2'
    dest: '/etc/security/limits.d/91-hpc-limits.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Copy 91-hpc-sysctl.conf to /etc/sysctl.d/
  template:
    src: '91-hpc-sysctl.conf.j2'
    dest: '/etc/sysctl.d/91-hpc-sysctl.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: yes
  notify: activate sysctls

