---
- name: Configure repo
  trix_repos:
    remote_repo: "{{ item.repo }}"
    remote_key:  "{{ item.key | default(None)}}"
    local_repo:  "{{ trix_local_repo_baseurl }}"
    local_key:   "{{ trix_local_repo_key | default(None) }}"
    name:        "{{ item.name | default(None) }}"
    use_local:   "{{ local_install | default(False) }}"
  with_items: "{{ repos }}"
  tags: install-only

- name: Disable normal CentOS repos when using CentOS-Vault repo
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: "{{ item }}"
    option: enabled
    value: 0
  with_items:
      - base
      - centosplus
      - extras
      - updates
  when: 
    - use_centos_vault|bool
    - not local_install

# Disable all remote repos (without *-local suffix)
# If we have local install
#
- block:

  # FIXME
  # Was trying to do it via yum_repos, lineinfile or ini_file
  # modules. Got monstrous construction at the end.
  - name: Install yum-utils to make yum-config-manager available
    yum:
      name: yum-utils
      state: installed

  - name: Disable all repo without '*-local' suffix
    shell: >
      yum-config-manager  \
      | sed -n 's/^\[\(.*\)\]$/\1/p' \
      | egrep -v "\-local$" \
      | xargs yum-config-manager --disable {}

    args:
      warn: no

  when: local_install
